DROP TABLE `Customer Information`;

CREATE DATABASE `Banking Analysis 1`;
USE `Banking Analysis 1`;
CREATE TABLE IF NOT EXISTS `Customer Information` (
`S.No` int not null,
`Customer Id` int,
`Customer Name` Varchar (40),
`Account Number` int,
`Account Type` varchar(25),
`Account Status` varchar(25),
`Branch Name` varchar(40),
`Branch Code` int,
`Customer Age` int,
`Customer Marital Status` varchar(20),
`Customer Location` varchar(35));

SELECT * FROM `Customer Information`;

INSERT INTO `Customer Information`(`S.No`,`Customer Id`,`Customer Name`,`Account Number`,`Account Type`, `Account Status`,`Branch Name`,`Branch Code`,`Customer Age`,`Customer Marital Status`,`Customer Location`) VALUES (1,89011,'Raja',784596651,'Savings Account','Active','TDPR',1111,28,'Married','Cuddalore');
INSERT INTO `Customer Information`(`S.No`,`Customer Id`,`Customer Name`,`Account Number`,`Account Type`, `Account Status`,`Branch Name`,`Branch Code`,`Customer Age`,`Customer Marital Status`) VALUES (2,89012,'Ramesh',647896651,'Current Account','Active','TDPR',1111,35,'Married');
INSERT INTO `Customer Information`(`S.No`,`Customer Id`,`Customer Name`,`Account Number`,`Account Type`, `Account Status`,`Branch Name`,`Branch Code`,`Customer Age`,`Customer Marital Status`) VALUES (3,69215,'Harini',884596651,'Savings Account','Active','TDPR',1111,19,'Unmarried');
INSERT INTO `Customer Information`(`S.No`,`Customer Id`,`Customer Name`,`Account Number`,`Account Type`, `Account Status`,`Branch Code`,`Customer Age`,`Customer Marital Status`,`Customer Location`) VALUES (4,75908,'Suresh',784598974,'Savings Account','Active',5555,29,'Married','Cuddalore OT');
INSERT INTO `Customer Information`(`S.No`,`Customer Id`,`Customer Name`,`Account Number`,`Account Type`, `Account Status`,`Branch Name`,`Branch Code`,`Customer Age`,`Customer Marital Status`,`Customer Location`) VALUES (5,53011,'Kamalesh',584976651,'Savings Account','Active','MNJ',4545,17,'Unmarried','Cuddalore MNJ');
INSERT INTO `Customer Information`(`S.No`,`Customer Id`,`Customer Name`,`Account Number`,`Account Type`, `Account Status`,`Branch Name`,`Customer Age`,`Customer Marital Status`,`Customer Location`) VALUES (6,91016,'Kumar',294590618,'Current Account','Active','TDPR',26,'Married','Cuddalore');
INSERT INTO `Customer Information`(`S.No`,`Customer Id`,`Customer Name`,`Account Number`,`Account Type`, `Account Status`,`Branch Name`,`Branch Code`,`Customer Age`,`Customer Marital Status`,`Customer Location`) VALUES (7,65811,'Ramya',889996651,'Savings Account','Active','CUPJ',5555,24,'Married','Cuddalore OT');
INSERT INTO `Customer Information`(`S.No`,`Customer Id`,`Customer Name`,`Account Number`,`Account Type`, `Account Status`,`Branch Code`,`Customer Age`,`Customer Marital Status`,`Customer Location`) VALUES (8,58612,'Gopi',689196651,'Current Account','Active',1111,46,'Married','Cuddalore');
INSERT INTO `Customer Information`(`S.No`,`Customer Id`,`Customer Name`,`Account Number`,`Account Type`, `Account Status`,`Branch Name`,`Branch Code`,`Customer Age`,`Customer Marital Status`,`Customer Location`) VALUES (9,91618,'Hari',634196651,'Savings Account','Active','MNJ',4545,15,'Unnarried','Cuddalore MNJ');
INSERT INTO `Customer Information`(`S.No`,`Customer Id`,`Customer Name`,`Account Number`,`Account Type`, `Account Status`,`Branch Name`,`Branch Code`,`Customer Age`,`Customer Marital Status`,`Customer Location`) VALUES (10,39098,'Roshni',305593662,'Current Account','Inactive','MNJ',4545,63,'Married','Cuddalore MNJ');

INSERT INTO `Customer Information`(`S.No`,`Customer Id`,`Customer Name`,`Account Number`,`Account Type`, `Account Status`,`Branch Name`,`Branch Code`,`Customer Age`,`Customer Marital Status`,`Customer Location`) VALUES (11,74098,'Rooban',804593652,'Current Account','Inactive','VRCM',1001,68,'Married','Virudhachalam');
INSERT INTO `Customer Information`(`S.No`,`Customer Id`,`Customer Name`,`Account Number`,`Account Type`, `Account Status`,`Branch Name`,`Branch Code`,`Customer Age`,`Customer Marital Status`,`Customer Location`) VALUES (12,71597,'Mary',834543601,'Savings Account','Inactive','VRCM',1001,45,'Married','Virudhachalam');
INSERT INTO `Customer Information`(`S.No`,`Customer Id`,`Customer Name`,`Account Number`,`Account Type`, `Account Status`,`Branch Name`,`Branch Code`,`Customer Age`,`Customer Marital Status`,`Customer Location`) VALUES (13,99023,'Chitra Devi',457593650,'Current Account','Active','VRCM',1001,58,'Married','Virudhachalam');
INSERT INTO `Customer Information`(`S.No`,`Customer Id`,`Customer Name`,`Account Number`,`Account Type`, `Account Status`,`Branch Name`,`Branch Code`,`Customer Age`,`Customer Location`) VALUES (14,30398,'Guru',224593656,'Current Account','Inactive','VPR',2222,44,'Vaepur');
INSERT INTO `Customer Information`(`S.No`,`Customer Id`,`Customer Name`,`Account Number`,`Account Type`, `Account Status`,`Branch Code`,`Customer Age`,`Customer Marital Status`,`Customer Location`) VALUES (15,90008,'Prasanth',974503654,'Savings Account','Active',1001,59,'Married','Virudhachalam');
INSERT INTO `Customer Information`(`S.No`,`Customer Id`,`Customer Name`,`Account Number`,`Account Type`, `Account Status`,`Branch Name`,`Customer Age`,`Customer Marital Status`,`Customer Location`) VALUES (16,13942,'Fazil',987593831,'Savings Account','Active','VRCM',38,'Married','Virudhachalam');
INSERT INTO `Customer Information`(`S.No`,`Customer Id`,`Customer Name`,`Account Number`,`Account Type`, `Account Status`,`Branch Name`,`Branch Code`,`Customer Age`,`Customer Marital Status`,`Customer Location`) VALUES (17,30928,'Gugan',299591652,'Current Account','Active','VPR',2222,34,'Married','Vaepur');
INSERT INTO `Customer Information`(`S.No`,`Customer Id`,`Customer Name`,`Account Number`,`Account Type`, `Account Status`,`Branch Name`,`Customer Age`,`Customer Marital Status`,`Customer Location`) VALUES (18,72040,'Bala',304553662,'Savings Account','Active','VPR',32,'Married','Vaepur');
INSERT INTO `Customer Information`(`S.No`,`Customer Id`,`Customer Name`,`Account Number`,`Account Type`, `Account Status`,`Branch Name`,`Customer Age`,`Customer Marital Status`,`Customer Location`) VALUES (19,72044,'Barani',304553642,'Savings Account','Active','VPR',35,'Married','Vaepur');
INSERT INTO `Customer Information`(`S.No`,`Customer Id`,`Customer Name`,`Account Number`,`Account Type`, `Account Status`,`Branch Name`,`Branch Code`,`Customer Age`,`Customer Marital Status`,`Customer Location`) VALUES (20,74041,'Keerthana',224043662,'Current Account','Active','VRCM',1001,30,'Unmarried','Virudhachalam');

INSERT INTO `Customer Information`(`S.No`,`Customer Id`,`Customer Name`,`Account Number`,`Account Type`, `Account Status`,`Branch Name`,`Branch Code`,`Customer Age`,`Customer Marital Status`) VALUES (21,29011,'Rakesh',284593351,'Savings Account','Active','TDPR',1111,28,'Married');
INSERT INTO `Customer Information`(`S.No`,`Customer Id`,`Customer Name`,`Account Number`,`Account Type`, `Account Status`,`Branch Name`,`Branch Code`,`Customer Age`,`Customer Marital Status`,`Customer Location`) VALUES (22,34016,'Nandha',432596653,'Current Account','Active','TDPR',1111,24,'Married','Cuddalore');
INSERT INTO `Customer Information`(`S.No`,`Customer Id`,`Customer Name`,`Account Number`,`Account Type`, `Account Status`,`Branch Name`,`Customer Age`,`Customer Marital Status`) VALUES (23,34013,'Maha',424596557,'Current Account','Active','TDPR',28,'Married');
INSERT INTO `Customer Information`(`S.No`,`Customer Id`,`Customer Name`,`Account Number`,`Account Type`, `Account Status`,`Branch Name`,`Branch Code`,`Customer Age`,`Customer Marital Status`,`Customer Location`) VALUES (24,99303,'Gopal',784596000,'Savings Account','Active','VRCM',1001,55,'Unmarried','Cuddalore');
INSERT INTO `Customer Information`(`S.No`,`Customer Id`,`Customer Name`,`Account Number`,`Account Type`, `Account Status`,`Branch Name`,`Branch Code`,`Customer Age`,`Customer Marital Status`) VALUES (25,33061,'Raja',999596655,'Savings Account','Inactive','TDPR',1111,67,'Married');
INSERT INTO `Customer Information`(`S.No`,`Customer Id`,`Customer Name`,`Account Number`,`Account Type`, `Account Status`,`Branch Name`,`Branch Code`,`Customer Age`,`Customer Marital Status`,`Customer Location`) VALUES (26,84611,'Rajarajan',356456651,'Savings Account','Active','MNJ',4545,48,'Married','Cuddalore MNJ');
INSERT INTO `Customer Information`(`S.No`,`Customer Id`,`Customer Name`,`Account Number`,`Account Type`, `Account Status`,`Branch Name`,`Branch Code`,`Customer Age`,`Customer Marital Status`,`Customer Location`) VALUES (27,85741,'Praveen',264598651,'Savings Account','Active','VPR',2222,38,'Married','Vaepur');
INSERT INTO `Customer Information`(`S.No`,`Customer Id`,`Customer Name`,`Account Number`,`Account Type`, `Account Status`,`Branch Name`,`Branch Code`,`Customer Age`,`Customer Marital Status`,`Customer Location`) VALUES (28,92114,'Malar',224556758,'Current Account','Inactive','MNJ',1111,45,'Unmarried','Cuddalore MNJ');
INSERT INTO `Customer Information`(`S.No`,`Customer Id`,`Customer Name`,`Account Number`,`Account Type`, `Account Status`,`Branch Name`,`Branch Code`,`Customer Age`,`Customer Marital Status`,`Customer Location`) VALUES (29,53413,'Dharshini',444516651,'Savings Account','Active','TDPR',1111,42,'Married','Cuddalore');
INSERT INTO `Customer Information`(`S.No`,`Customer Id`,`Customer Name`,`Account Number`,`Account Type`, `Account Status`,`Branch Name`,`Branch Code`,`Customer Age`,`Customer Marital Status`,`Customer Location`) VALUES (30,55011,'Narmadha',664596651,'Current Account','Active','CUPJ',5555,26,'Married','Cuddalore OT');

INSERT INTO `Customer Information`(`S.No`,`Customer Id`,`Customer Name`,`Account Number`,`Account Type`, `Account Status`,`Branch Name`,`Branch Code`,`Customer Age`,`Customer Marital Status`,`Customer Location`) VALUES (31,16014,'Karthi',784596690,'Current Account','Inactive','MNJ',4545,58,'Unmarried','Cuddalore MNJ');
INSERT INTO `Customer Information`(`S.No`,`Customer Id`,`Customer Name`,`Account Number`,`Account Type`, `Account Status`,`Branch Name`,`Branch Code`,`Customer Age`,`Customer Marital Status`,`Customer Location`) VALUES (32,90002,'Baranesh',344006651,'Savings Account','Active','TDPR',1111,14,'Unmarried','Cuddalore');
INSERT INTO `Customer Information`(`S.No`,`Customer Id`,`Customer Name`,`Account Number`,`Account Type`, `Account Status`,`Customer Age`,`Customer Marital Status`,`Customer Location`) VALUES (33,10010,'Magesh',484596999,'Current Account','Active',38,'Married','Vaepur');
INSERT INTO `Customer Information`(`S.No`,`Customer Id`,`Customer Name`,`Account Number`,`Account Type`, `Account Status`,`Branch Name`,`Branch Code`,`Customer Age`,`Customer Marital Status`) VALUES (34,95131,'Malini',554596622,'Current Account','Active','VRCM',1001,69,'Married');
INSERT INTO `Customer Information`(`S.No`,`Customer Id`,`Customer Name`,`Account Number`,`Account Type`, `Account Status`,`Branch Name`,`Branch Code`,`Customer Age`,`Customer Marital Status`,`Customer Location`) VALUES (35,89441,'Boopathi',714296621,'Savings Account','Active','CUPJ',5555,16,'Unmarried','Cuddalore OT');
INSERT INTO `Customer Information`(`S.No`,`Customer Id`,`Customer Name`,`Account Number`,`Account Type`, `Account Status`,`Branch Name`,`Branch Code`,`Customer Age`,`Customer Marital Status`,`Customer Location`) VALUES (36,86041,'Kishore',754798691,'Current Account','Active','TDPR',1111,28,'Married','Cuddalore');
INSERT INTO `Customer Information`(`S.No`,`Customer Id`,`Customer Name`,`Account Number`,`Account Type`, `Account Status`,`Branch Name`,`Branch Code`,`Customer Age`,`Customer Marital Status`,`Customer Location`) VALUES (37,80110,'RajaYogesh',885593620,'Savings Account','Active','VPR',2222,58,'Married','Vaepur');
INSERT INTO `Customer Information`(`S.No`,`Customer Id`,`Customer Name`,`Account Number`,`Account Type`, `Account Status`,`Branch Name`,`Branch Code`,`Customer Age`,`Customer Marital Status`,`Customer Location`) VALUES (38,89040,'Gayathiri',999596651,'Savings Account','Active','TDPR',1111,45,'Married','Cuddalore');
INSERT INTO `Customer Information`(`S.No`,`Customer Id`,`Customer Name`,`Account Number`,`Account Type`, `Account Status`,`Branch Code`,`Customer Age`,`Customer Marital Status`,`Customer Location`) VALUES (39,89500,'Mohan',464596667,'Savings Account','Active',4545,28,'Married','Cuddalore MNJ');
INSERT INTO `Customer Information`(`S.No`,`Customer Id`,`Customer Name`,`Account Number`,`Account Type`, `Account Status`,`Branch Name`,`Branch Code`,`Customer Age`,`Customer Marital Status`,`Customer Location`) VALUES (40,89600,'Kousik',223396651,'Current Account','Active','TDPR',1111,23,'Married','Cuddalore');

INSERT INTO `Customer Information`(`S.No`,`Customer Id`,`Customer Name`,`Account Number`,`Account Type`, `Account Status`,`Branch Name`,`Branch Code`,`Customer Age`,`Customer Marital Status`,`Customer Location`) VALUES (41,99001,'Kamal',464396651,'Savings Account','Inactive','TDPR',1111,28,'Married','Cuddalore');
INSERT INTO `Customer Information`(`S.No`,`Customer Id`,`Customer Name`,`Account Number`,`Account Type`, `Account Status`,`Branch Name`,`Branch Code`,`Customer Age`,`Customer Marital Status`,`Customer Location`) VALUES (42,89011,'lalitha',581299651,'Savings Account','Active','MNJ',4545,43,'Married','Cuddalore MNJ');
INSERT INTO `Customer Information`(`S.No`,`Customer Id`,`Customer Name`,`Account Number`,`Account Type`, `Account Status`,`Branch Name`,`Branch Code`,`Customer Age`,`Customer Marital Status`) VALUES (43,89000,'Raja',784596651,'Savings Account','Active','TDPR',1111,28,'Married');
INSERT INTO `Customer Information`(`S.No`,`Customer Id`,`Customer Name`,`Account Number`,`Account Type`, `Account Status`,`Branch Name`,`Branch Code`,`Customer Age`,`Customer Marital Status`,`Customer Location`) VALUES (44,89810,'Siva',784126122,'Savings Account','Active','TDPR',1111,52,'Married','Cuddalore');
INSERT INTO `Customer Information`(`S.No`,`Customer Id`,`Customer Name`,`Account Number`,`Account Type`, `Account Status`,`Branch Name`,`Branch Code`,`Customer Age`,`Customer Marital Status`,`Customer Location`) VALUES (45,90000,'Charan',884517612,'Savings Account','Active','TDPR',1111,55,'Married','Cuddalore');
INSERT INTO `Customer Information`(`S.No`,`Customer Id`,`Customer Name`,`Account Number`,`Account Type`, `Account Status`,`Branch Name`,`Branch Code`,`Customer Age`,`Customer Marital Status`,`Customer Location`) VALUES (46,79041,'Jagan',384596631,'Current Account','Active','MNJ',4545,62,'Married','Cuddalore MNJ');
INSERT INTO `Customer Information`(`S.No`,`Customer Id`,`Customer Name`,`Account Number`,`Account Type`, `Account Status`,`Branch Name`,`Branch Code`,`Customer Age`,`Customer Marital Status`,`Customer Location`) VALUES (47,39012,'Kala',284566659,'Savings Account','Inactive','TDPR',1111,18,'Unmarried','Cuddalore');
INSERT INTO `Customer Information`(`S.No`,`Customer Id`,`Customer Name`,`Account Number`,`Account Type`, `Account Status`,`Branch Name`,`Branch Code`,`Customer Age`,`Customer Marital Status`,`Customer Location`) VALUES (48,29001,'Kamala',284596000,'Current Account','Active','TDPR',1111,28,'Married','Cuddalore');
INSERT INTO `Customer Information`(`S.No`,`Customer Id`,`Customer Name`,`Account Number`,`Account Type`, `Account Status`,`Branch Name`,`Branch Code`,`Customer Age`,`Customer Marital Status`,`Customer Location`) VALUES (49,35111,'Vignesh',424596001,'Savings Account','Active','TDPR',1111,48,'Married','Cuddalore');
INSERT INTO `Customer Information`(`S.No`,`Customer Id`,`Customer Name`,`Account Number`,`Account Type`, `Account Status`,`Branch Name`,`Branch Code`,`Customer Age`,`Customer Marital Status`,`Customer Location`) VALUES (50,20011,'Kandha Samy',414596690,'Current Account','Inactive','TDPR',1111,38,'Married','Cuddalore');